#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

enum geometricToolSelected
{
    NO_TOOL = 0,
    MOVE_OBJECTS = 1,
    CREATE_POINT = 2,
    CREATE_SEGMENT = 3,
    CREATE_LINE = 4,
    CREATE_CIRCLE_DB2 = 5,
    CREATE_CIRCLE_DB3 = 6,

    CREATE_ALTITUDE_FOOT = 101,
    CREATE_MIDPOINT = 102,
    CREATE_PERPENDICULAR_BISECTOR = 103,
    CREATE_ANGLE_BISECTOR = 104,
    CREATE_OUTSIDE_ANGLE_BISECTOR = 105,

    DELETE_OBJECT = 201,
};

enum pointType
{
    FREE = 1,
    RELATIVE = 2,
    LOCKED_CROSSPOINT = 3,
    LOCKED_ALTITUDE_FOOT = 4,
    LOCKED_MIDPOINT = 5,
    LOCKED_PERPENDICULAR_BISECTOR = 6,
    LOCKED_ANGLE_BISECTOR = 7,
    LOCKED_OUTSIDE_ANGLE_BISECTOR = 98,

    NO_POINT = 0,

    TEMPORARY_FREE = -1,
    TEMPORARY_RELATIVE = -2,
    TEMPORARY_LOCKED_CROSSPOINT = -3,
    TEMPORARY_LOCKED_ALTITUDE_FOOT = -4,
    TEMPORARY_LOCKED_MIDPOINT = -5,
    TEMPORARY_LOCKED_PERPENDICULAR_BISECTOR = -6,
    TEMPORARY_LOCKED_ANGLE_BISECTOR = -7,
    TEMPORARY_LOCKED_OUTSIDE_ANGLE_BISECTOR = -8,
};

enum geometryShape
{
    NO_SHAPE = 0,
    POINT = 1,
    SEGMENT = 2,
    LINE = 3,
    CIRCLE_DB2 = 4,
    CIRCLE_DB3 = 5
};
#endif // ENUMS_H_INCLUDED
